name: Flake Check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  flake-check:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]

    steps:
    - name: Checkout
      uses: actions/checkout@